site_name: ACES Documentation
copyright: Copyright &copy; 2024 Academy of Motion Picture Arts & Sciences

site_dir: site
docs_dir: docs

extra:
  generator: false
  homepage: https://www.acescentral.com
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/academyaces
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/AcademyACESColor/
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/channel/UCnmCugF923ta50EFzxgQmjw
    - icon: fontawesome/brands/github
      link: https://www.github.com/ampas
    - icon: fontawesome/solid/fish
      link: assets/pdfs/kodak-grey-card.pdf
      name: The Great Cod

extra_css: 
  - stylesheets/extra.css

theme:
  name: 'material'
  # custom_dir: overrides
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.tracking
    - navigation.expand
    - navigation.top
    - navigation.instant
    - navigation.instant.progress
    - navigation.prue
    - toc.follow
    - content.tooltips
  favicon: assets/images/favicon.png
  logo: assets/images/logo.png
  font:
    text: Pontano Sans
  icon:
    repo: fontawesome/brands/github
  palette:

    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/lightbulb-auto-outline
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: aces-light
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/lightbulb-outline
        name: Switch to system preference

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.snippets:
      auto_append:
        - includes/acronyms.md
  - pymdownx.magiclink
  - attr_list
  - md_in_html
  - abbr
  - def_list
  - toc:
      permalink: true
      toc_depth: 3
  - footnotes
  - admonition
  - pymdownx.details
  - meta
      
extra_javascript:
  - js/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  
plugins:
  - search
  - git-revision-date-localized:
      type: date
      timezone: America/Los_Angeles
      locale: en
      exclude:
          - index.md
      enabled: true

nav:
  - 'ACES Documentation': 
    - 'Getting Started':
      - 'Overview': index.md
      - 'What''s New in 2.0': background/whats-new.md
      - 'ACES v1 Feedback': background/listening-tour.md
      - 'Contribute to ACES': background/contribute.md    
    - 'Technical Details':
      - 'System Overview': background/overview.md
      - 'Organization': background/organization/index.md
      - 'Versioning': background/versioning.md
      - 'Transform IDs': transform-ids.md
  - 'System Components':
    - 'System Overview': system-components/system-overview.md
    - 'Encodings': 
      - 'Overview': encodings/overview.md
    - 'File Formats':
      - 'ACES Metadata File (AMF)': 
        - 'Introduction': amf/introduction.md
        - 'User Guide': amf/guides/index.md
      - 'Common LUT Format': 
        - 'Introduction': clf/introduction.md
    - 'Input Transforms': 
      - 'Introduction': system-components/input-transforms/index.md
    - 'Output Transforms': 
      - 'Introduction': system-components/output-transforms/technical-details/index.md
    - 'Look Transforms': 
      - 'Introduction': system-components/look-transforms/index.md
    - 'Reference Gamut Compression': 
      - 'Introduction': rgc/overview.md
      - 'User Guide': rgc/guides/rgc-user/index.md
    - 'Component Names': component-names/index.md        
  - 'Technical Details':
    - Encodings:
      - 'Derivation of the ACES White Point': white-point/index.md
      - 'ACES2065-1': encodings/aces2065-1.md
      - 'ACEScg': encodings/acescg.md
      - 'ACEScct': encodings/acescct.md
      - 'ACEScc': encodings/acescc.md
      - 'ACESproxy': encodings/acesproxy.md
      - 'APD (Academy Printing Density)': encodings/apd.md
      - 'ADX (Academy Density Exchange)': encodings/adx.md
    - 'File Formats':
      - 'ACES Metadata File (AMF)': 
        - 'Specification': amf/specification/index.md
      - 'Common LUT Format': 
        - 'Specification': clf/specification/index.md
        - 'Implementation Guide': clf/guides/index.md
    - 'Input Transforms': 
      - 'Procedure': https://www.dropbox.com/scl/fi/o0az9azz833t1sde8apfz/P-2013-001.pdf?rlkey=j7eqd4l0wpvbhpi72ayjvflka&e=1&dl=0
      - 'Tools': system-components/input-transforms/tools.md
    - 'Output Transforms': 
      - 'Overview': system-components/output-transforms/technical-details/index.md
      - 'Tone Mapping': system-components/output-transforms/technical-details/tone-mapping/index.md
      - 'Chroma Compression': system-components/output-transforms/technical-details/chroma-compression/index.md
      - 'Gamut Compression': system-components/output-transforms/technical-details/gamut-compression/index.md
      - 'White Limiting': system-components/output-transforms/technical-details/white-limiting/index.md
      - 'Display Encoding': system-components/output-transforms/technical-details/display-encoding/index.md
    - 'Look Transforms': 
      - 'Specification': system-components/look-transforms/specification.md
    - 'Reference Gamut Compression': 
      - 'Specification': rgc/specification/index.md
      - 'Implementation Guide': rgc/guides/rgc-implementation/index.md
    - 'Component Names': component-names/index.md        
  - 'Glossary': glossary/index.md

  # - 'ACES Standards':  tools/index.md
  # - 'Production Tool Guides':  tools/index.md
  # - 'Recommended Procedures': procedures/index.md
