site_name: ACES Documentation
copyright: Copyright &copy; 2024 Academy of Motion Picture Arts & Sciences

site_dir: site
docs_dir: docs

extra:
  generator: false
  homepage: https://www.acescentral.com
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/academyaces
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/AcademyACESColor/
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/channel/UCnmCugF923ta50EFzxgQmjw
    - icon: fontawesome/brands/github
      link: https://www.github.com/ampas
    - icon: fontawesome/solid/fish
      link: assets/pdfs/kodak-grey-card.pdf
      name: The Great Cod

extra_css: 
  - stylesheets/extra.css

theme:
  name: 'material'
  # custom_dir: overrides
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.tracking
    - navigation.expand
    - navigation.top
    - navigation.instant
    - navigation.instant.progress
    - navigation.prue
    - toc.follow
    - content.tooltips
  favicon: assets/images/favicon.png
  logo: assets/images/logo.png
  font:
    text: Pontano Sans
  icon:
    repo: fontawesome/brands/github
  palette:

    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/lightbulb-auto-outline
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: aces-light 
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/lightbulb-outline
        name: Switch to system preference

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.snippets:
      auto_append:
        - includes/acronyms.md
  - pymdownx.magiclink
  - attr_list
  - md_in_html
  - abbr
  - def_list
  - toc:
      permalink: true
      toc_depth: 3
  - footnotes
  - admonition
  - pymdownx.details
  - meta
      
extra_javascript:
  - js/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  
plugins:
  - search
  - git-revision-date-localized:
      type: date
      timezone: America/Los_Angeles
      locale: en
      exclude:
          - index.md
      enabled: true

nav:
  - 'ACES Documentation': 
    - 'Getting Started': index.md
    - 'System Overview': overview.md
    - 'Component Names': component-names/index.md
  - 'Technical Documentation':
    - 'Overview': system-components/overview/index.md
    - 'Organization': system-components/organization/index.md
    - 'Encodings':
      - 'ACEScg': acescg/index.md
      - 'ACEScct': acescct/index.md
      - 'ACEScc': acescc/index.md
      - 'ACESproxy': acesproxy/index.md
    - 'Transforms':
      - 'Reference Gamut Compression': rgc/specification/index.md
      - 'Output Transforms': output-transforms/specification/ot-gamut-compression/index.md
    - 'File Formats':
      - 'ACES Metadata File': 
        - 'Specification': amf/specification/index.md
        - 'User Guide': amf/guides/index.md
      - 'Common LUT Format': 
        - 'Specification': clf/specification/index.md
        - 'Implementation Guide': clf/guides/index.md
  - 'Recommended Procedures': procedures/index.md
  - 'User Guides': workflows/index.md
  - 'Production Tool Guides':  tools/index.md
  - 'Glossary': glossary/index.md
