site_name: ACES Documentation
copyright: Copyright &copy; 2024 Academy of Motion Picture Arts & Sciences

site_dir: site
docs_dir: docs

extra:
  generator: false
  homepage: https://www.acescentral.com
  social:
    - icon: fontawesome/brands/github
      link: https://www.github.com/ampas
    - icon: fontawesome/solid/fish
      link: assets/pdfs/kodak-grey-card.pdf
      name: The Great Cod

extra_css:
  - stylesheets/extra.css

theme:
  name: 'material'
  # custom_dir: overrides
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.tracking
    - navigation.expand
    - navigation.top
    - navigation.instant
    - navigation.instant.progress
    - toc.follow
    - content.tooltips
  favicon: assets/images/favicon.png
  logo: assets/images/aces-acescentral-color.png
  font:
    text: Pontano Sans
  icon:
    repo: fontawesome/brands/github
    annotation: material/plus-circle
  palette:

    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/lightbulb-auto-outline
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: aces-light
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/lightbulb-outline
        name: Switch to system preference

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.snippets:
      auto_append:
        - includes/acronyms.md
  - pymdownx.magiclink
  - attr_list
  - md_in_html
  - abbr
  - def_list
  - toc:
      permalink: true
      toc_depth: 3
  - footnotes
  - admonition
  - pymdownx.details
  - meta

extra_javascript:
  - js/image-wipe.js
  - js/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

plugins:
  - search
  - git-revision-date-localized:
      type: date
      timezone: America/Los_Angeles
      locale: en
      exclude:
          - index.md
      enabled: true
  - open-in-new-tab

nav:
  - 'Introduction':
    - 'Getting Started': index.md
    - 'Overview of ACES':
      - 'ACES System': background/overview.md
      - 'Encodings': encodings/introduction.md
      - 'Input Transforms': system-components/input-transforms/index.md
      - 'Output Transforms': system-components/output-transforms/index.md
      - 'Look Transforms': system-components/look-transforms/index.md
      - 'Reference Gamut Compression': rgc/overview.md
      - 'ACES Metadata File (AMF)': amf/guides/user/index.md
      - 'Reference Code': background/organization/index.md
      - 'Common LUT Format': clf/introduction.md
    - 'About ACES 2':
      - 'General': background/about-aces-2.md
      - 'Rendering Transform': background/about-rendering.md
    - 'Background Information':
      - 'ACES 1 Feedback': background/v1-feedback.md
      - 'Listening Tour': background/listening-tour.md

  - 'Technical Details':
    - Introduction: home-technical.md
    - Encodings:
      - 'Overview': encodings/overview.md
      - 'ACES2065-1': encodings/aces2065-1.md
      - 'ACEScg': encodings/acescg.md
      - 'ACEScct': encodings/acescct.md
      - 'ACEScc': encodings/acescc.md
      - 'ACESproxy': encodings/acesproxy.md
      - 'APD (Academy Printing Density)': encodings/apd.md
      - 'ADX (Academy Density Exchange)': encodings/adx.md
      - 'Derivation of the ACES White Point': white-point/index.md
    - 'File Formats':
      - 'ACES Metadata File (AMF)':
        - 'Specification': amf/specification/index.md
        - 'Implementation Guide': amf/guides/implementation/index.md
      - 'Common LUT Format':
        - 'Specification': clf/specification/index.md
        - 'Implementation Guide': clf/guides/index.md
    - Transforms:
      - 'Input Transforms':
        - 'Procedure': https://www.dropbox.com/scl/fi/o0az9azz833t1sde8apfz/P-2013-001.pdf?rlkey=j7eqd4l0wpvbhpi72ayjvflka&e=1&dl=0
        - 'Capture Guide': system-components/input-transforms/capture-guide.md
      - 'Output Transforms':
        - 'Structure':
          - 'Overview': system-components/output-transforms/technical-details/rendering-overview.md
          - 'Tone Mapping': system-components/output-transforms/technical-details/tone-mapping/index.md
          - 'Chroma Compression': system-components/output-transforms/technical-details/chroma-compression/index.md
          - 'Gamut Compression': system-components/output-transforms/technical-details/gamut-compression/index.md
          - 'White Limiting': system-components/output-transforms/technical-details/white-limiting/index.md
          - 'Display Encoding': system-components/output-transforms/technical-details/display-encoding/index.md
        - 'Preset Parameters': system-components/output-transforms/parameters.md
        - 'Implementor Notes': system-components/output-transforms/implementer-notes.md
      - 'Look Transforms':
        - 'Use Cases': system-components/look-transforms/use-cases.md
        - 'Specification': system-components/look-transforms/specification.md
      - 'Reference Gamut Compression':
        - 'Specification': rgc/specification/index.md
        - 'Implementation Guide': rgc/guides/rgc-implementation/index.md
        - 'User Guide': rgc/guides/rgc-user/index.md
      - 'Transform IDs': system-components/transform-id-spec.md
    - 'ACES Standards': https://www.smpte.org/standards/aces-standards

  - 'Glossary': glossary/index.md

  # - 'ACES Standards':  tools/index.md
  # - 'Production Tool Guides':  tools/index.md
  # - 'Recommended Procedures': procedures/index.md
  # - 'Contribute to ACES': background/contribute.md
  # - 'Tools': system-components/input-transforms/tools.md
